package Lab1;

//For the purpose of a software for keeping track of the revenue generated by employees in the sales department, define
// a QuarterlySales class that stores the number of sales, the revenue generated by each sale and the number
// of the quarter.
//
//Then define another SalesPerson class for which a name(string) and an array of quarterly sales (exactly 4)
// are stored. For the classes implement the appropriate constructors and methods for the correct execution of
// the program.
//
//Implement the following requirements:
//
//• Method `int sumSales(SalesPerson sp)' which will return sum of all the revenues in all
// quarters generated by the given worker.
//
//• Method `SalesPerson salesChampion(SalesPerson [] arr)' which for the given array of sales employees will
// return the worker with the most generated revenue (of all quarters)
//
//• Add the `main' method, which will initialize an array of sales persons and quarters according to the input
// test cases. The number of sales employees is read from input in the first line, and then for each employee
// the name is read in the first line, and then for each of the quarters for that employee in the first line
// we have the number of sales, and then in the next line the revenue generated by each of those sales.
//
//• On standard output, print the array of sales employees using the method `void table(SalesPerson [] arr)',
// which will print a display for the array of sales persons in the following format
// (three spaces are used for printing space):
import java.util.Scanner;

class QuarterlySales {

    private int numOfSales;
    private int [] revenues;
    private int quarterNo;

    public QuarterlySales(int numOfSales, int[] revenues, int quarterNo) {
        this.numOfSales = numOfSales;
        this.revenues = revenues;
        this.quarterNo = quarterNo;
    }
    @Override
    public String toString() {
        return String.valueOf(getRevenue());
    }

    public int getRevenue() {
        int sum = 0;
        for(int revenue : revenues){
            sum+=revenue;
        }
        return sum;
    }
}



class SalesPerson {

    private String name;
    private QuarterlySales [] quarters;

    public SalesPerson(String name, QuarterlySales[] quarters) {
        this.name = name;
        this.quarters = quarters;
    }
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(name);
        for(QuarterlySales quarter : quarters){
            sb.append("   ").append(quarter);
        }
        sb.append("   ").append(getTotalRevenue());
        return sb.toString();
    }

    public int getTotalRevenue(){
        int total = 0;
        for(QuarterlySales quarter: quarters){
            total += quarter.getRevenue();
        }
        return total;
    }


    public String getName() {
        return this.name;
    }
}



 class Main {

    public static SalesPerson salesChampion(SalesPerson [] arr)
    {
        SalesPerson champion = arr[0];
        for(SalesPerson sp : arr) {
            if(sp.getTotalRevenue() > champion.getTotalRevenue()) {
                champion = sp;
            }
        }
        return champion;
    }
    public static void table(SalesPerson [] arr)
    {
        System.out.println("SP   1   2   3   4   Total");
        for(SalesPerson sp : arr) {
            System.out.println(sp);
        }
        System.out.println();
    }
    public static int sumSales(SalesPerson sp) {
        return sp.getTotalRevenue();
    }

    public static void main(String[] args) {

        int n;
        Scanner input = new Scanner(System.in);
        n = input.nextInt();
        SalesPerson [] arr = new SalesPerson[n];
        for(int i=0;i<n;i++)
        {
            String name = input.next();
            QuarterlySales[] quarters = new QuarterlySales[4];

            for (int j = 0; j < 4; j++) {
                int numOfSales = input.nextInt();
                int[] revenues = new int[numOfSales];

                for (int k = 0; k < numOfSales; k++) {
                    revenues[k] = input.nextInt();
                }

                quarters[j] = new QuarterlySales(numOfSales, revenues, j + 1);
            }

            arr[i] = new SalesPerson(name, quarters);
        }


        table(arr);
        System.out.println("SALES CHAMPION: " + salesChampion(arr).getName());

    }
}